// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7ICmF6f30s8Tt_Jsg8AZlc4a4Cqzr2g',
    appId: '1:77614029235:web:f34af04b88f1116bf5d3c6',
    messagingSenderId: '77614029235',
    projectId: 'portal-12121',
    authDomain: 'portal-12121.firebaseapp.com',
    storageBucket: 'portal-12121.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PLDWM0eVgHzt0niPWjentOBrBZ2tKlk',
    appId: '1:77614029235:android:572486212b4c06d3f5d3c6',
    messagingSenderId: '77614029235',
    projectId: 'portal-12121',
    storageBucket: 'portal-12121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5X1oinN7CXAntVtJJBWMBQ1Nm0TiDOV8',
    appId: '1:77614029235:ios:5698b968215299a7f5d3c6',
    messagingSenderId: '77614029235',
    projectId: 'portal-12121',
    storageBucket: 'portal-12121.appspot.com',
    iosClientId: '77614029235-6kmibl3cmrnjt3ierf9bpjde62s5a33n.apps.googleusercontent.com',
    iosBundleId: 'com.example.siteRenaultRizzi',
  );
}
